### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by Valiceemo** [winkidney/PIFanTuner#1]
Not sure if this project is still alive / monitored / maintained, but ill try.

During install I get an error:

```
pi@media-pi:~/git-clones/PIFanTuner $ sudo python setup.py install
running install
running bdist_egg
running egg_info
creating PIFanTuner.egg-info
writing requirements to PIFanTuner.egg-info/requires.txt
writing PIFanTuner.egg-info/PKG-INFO
writing top-level names to PIFanTuner.egg-info/top_level.txt
writing dependency_links to PIFanTuner.egg-info/dependency_links.txt
writing entry points to PIFanTuner.egg-info/entry_points.txt
writing manifest file 'PIFanTuner.egg-info/SOURCES.txt'
reading manifest file 'PIFanTuner.egg-info/SOURCES.txt'
writing manifest file 'PIFanTuner.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib.linux-armv7l-2.7
copying pi_fan_tuner.py -> build/lib.linux-armv7l-2.7
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
copying build/lib.linux-armv7l-2.7/pi_fan_tuner.py -> build/bdist.linux-armv7l/egg
byte-compiling build/bdist.linux-armv7l/egg/pi_fan_tuner.py to pi_fan_tuner.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying PIFanTuner.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying PIFanTuner.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying PIFanTuner.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying PIFanTuner.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying PIFanTuner.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying PIFanTuner.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/PIFanTuner-0.0.1-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing PIFanTuner-0.0.1-py2.7.egg
Copying PIFanTuner-0.0.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding PIFanTuner 0.0.1 to easy-install.pth file
Installing pi-fan-tuner script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/PIFanTuner-0.0.1-py2.7.eggProcessing dependencies for PIFanTuner==0.0.1
Searching for cmdtree>=0.0.3
Reading https://pypi.python.org/simple/cmdtree/
Best match: cmdtree 0.0.5.linux-x86-64
Downloading https://pypi.python.org/packages/a6/bd/275b7d73bf7e88682cebb3167761d77d3f5a5565e015e1aa72b3957be718/cmdtree-0.0.5.linux-x86_64.tar.gz#md5=ceb5052d412c2869d2945fa8e7184b85
Processing cmdtree-0.0.5.linux-x86_64.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-zNOahi/cmdtree-0.0.5.linux-x86_64.tar.gz
pi@media-pi:~/git-clones/PIFanTuner $ pi-fan-tuner --help
Traceback (most recent call last):
  File "/usr/local/bin/pi-fan-tuner", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cmdtree>=0.0.3
pi@media-pi:~/git-clones/PIFanTuner $
```

**Comment by Valiceemo** [comment]
ignore this and accept my apologies.

`cmdtree` was not installed on my Pi.
